### ISSUE TITLE
Not taking full screen

### ISSUE THREAD

**Issue by amosaxe** [birdwingo/react-native-instagram-stories#36]
I have tried everything but it never takes full screen, theres always some area left at the top and bottom.

**Comment by Lipo11** [comment]
Hello, can you send us the image you provided and screenshoot from your device? Thanks.

**Comment by amosaxe** [comment]
Hi, sure, i am attaching the screenshot as well as the image used here. 

![gh](https://github.com/birdwingo/react-native-instagram-stories/assets/122282992/1f8b66cd-3bc5-4afd-8684-5a8aab3d6836)
![Screenshot_2024-01-24-15-51-32-703_com modaltest](https://github.com/birdwingo/react-native-instagram-stories/assets/122282992/9c8972c9-0ef5-41ac-bb4b-1b34dca9d333)

**Comment by amosaxe** [comment]
Adding the whole code that we are using

`import React from 'react';
import {View} from 'react-native';
import InstagramStories from '@birdwingo/react-native-instagram-stories';

const App = () => {
  const {width: SCREEN_WIDTH, height: SCREEN_HEIGHT} = Dimensions.get('window');
  const stories = [
    {
      id: 'user1',
      name: 'User 1',
      imgUrl:
        'https://banner2.cleanpng.com/20190606/xch/kisspng-faded-music-mask-disc-jockey-darkside-5cf8dd7baf38c5.5844290115598134997177.jpg',
      stories: [
        {
          id: 'story1',
          sourceUrl:
            'https://i1.sndcdn.com/artworks-IrhmhgPltsdrwMu8-thZohQ-t500x500.jpg',
        },
        {
          id: 'story2',
          sourceUrl:
            'https://i.pinimg.com/originals/8e/27/58/8e2758477b11d7c44d8defe9bf08ffb6.jpg',
          mediaType: 'image',
        },
      ],
    },
    {
      id: 'user1',
      name: 'User 1',
      imgUrl:
        'https://banner2.cleanpng.com/20190606/xch/kisspng-faded-music-mask-disc-jockey-darkside-5cf8dd7baf38c5.5844290115598134997177.jpg',
      stories: [
        {
          id: 'story1',
          sourceUrl:
            'https://i1.sndcdn.com/artworks-IrhmhgPltsdrwMu8-thZohQ-t500x500.jpg',
        },
        {
          id: 'story2',
          sourceUrl:
            'https://i.pinimg.com/originals/8e/27/58/8e2758477b11d7c44d8defe9bf08ffb6.jpg',
          mediaType: 'image',
        },
      ],
    },
  ];

  return (
    <View>
      <InstagramStories
        stories={stories}
        containerStyle={{
          height: SCREEN_HEIGHT,
          width: SCREEN_WIDTH,
        }}
        backgroundColor="white"
      />
    </View>
  );
};

export default App;`

**Comment by Lipo11** [comment]
are you using new fabric arch enabled?

**Comment by amosaxe** [comment]
No.
Also,  I checked out the official Birdwingo app, and feels like this is the expected behaviour from the package. But, can you let me know where should I make the changes if I want to increase the height of the layout? I do understand the cubic animation will require us not to take full screen, but still the current layout looks a lot empty space.

**Comment by Lipo11** [comment]
Thanks for the info. This is not the expected behaviour and we will investigate for a fix. Can you tell us what phone are you using ( type and android version ).
Currently we are a busy a bit, i think we can check that next week.

**Comment by amosaxe** [comment]
Hi Sure,
Poco X2
Android 11 MIUI 12.

Also, as we are going to use this library extensively and are working to add many features, we are ready to be contribute as well, but have some doubts, which if cleared, can enable us to do the same.

**Comment by Lipo11** [comment]
Hello, we really love to cooperate with everyone, so pull request are really welcome! :) We just have a strict rules inside of company like: hold our linter and write new things globally ( example: "bottom button api" will not be acceptable, we are preferring footer component instead. ). Your bug should be fixed in the new today release, please let us know if its working correctly. See ya!

**Comment by Audeos** [comment]
Hey. The issue persists on my phone. I'm using Xiaomi Redmi Note 8 Pro, but it happens on iOS emulator too. It also pushes footer below the screen.
