### ISSUE TITLE
Only first frame of video is shown

### ISSUE THREAD

**Issue by geertvansoest** [birdwingo/react-native-instagram-stories#70]
Even when autoplay is enabled, sometimes, when a video story is opened the video is "frozen" and only the first frame is shown.

The biggest problem here is that the "progress bar" starts to fill up immediately and the user navigates to the next story if the bar is completely full, even if the video is not finished because it did not start or started later.

Another issue related to this is that pressing the screen may trigger the video to play. But this also triggers a user to navigate to the previous (if you press at the left half of the screen) or next story (if you press at the right half of the screen). Maybe this can be fixed to only navigate to the previous/next story if you press the - for example - left or right 50 pixels of the screen?

**Comment by Ahsanali012** [comment]
yes i am also facing the issue for video as video is played for first time . When switching between different stories the video is frozen and not playing

**Comment by geertvansoest** [comment]
@LukasFridmansky I think all other issues are fixed in 1.2.11, many thanks for that! But in that version, video stories are **always** "frozen" when we open them using the avatar list. If the stories modal is already opened en navigate to a video story by swiping left/right there is no problem.

**Comment by LukasFridmansky** [comment]
Is it android or iOS?

**Comment by geertvansoest** [comment]
iOS

**Comment by LukasFridmansky** [comment]
I will need to investigate it somehow. For me it works fine. I think the problem is the resume method, it is not called when modal is opened (because it is undefined). I have no idea why it works for me and not for you

**Comment by geertvansoest** [comment]
@LukasFridmansky It seems that this issue was caused at our side because we were still using version 5 from `react-native-video`, which doesn't includes the `resume()` method. After we updated to version 6, which is stable released previous month, this issue is fixed. Our apologies for the inconvenience. 😅

**Comment by LukasFridmansky** [comment]
No problem, thank you very much

**Comment by Audeos** [comment]
I have all of the packages up to date. But the issue still persists. On both Android device and iOS emulator, video stories play and end immediately.
